apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-circleci
  namespace: circleci
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-circleci
  storageClassName: azurefile-csi