apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id:  # az identity show --name $workloadIdentity --resource-group $resourceGroup --query clientId -o tsv
  labels:
    azure.workload.identity/use: "true"
  name: circleci-sa
  namespace: circleci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: circleci
  name: circleci-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: circleci-rolebinding
  namespace: circleci
subjects:
- kind: ServiceAccount
  name: circleci-sa
  namespace: circleci
roleRef:
  kind: Role
  name: circleci-role
  apiGroup: rbac.authorization.k8s.io