apiVersion: v1
kind: Namespace
metadata:
  name: circleci
  labels:
    name: circleci
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-kv-workload-identity
  namespace: circleci
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: # az identity show --name $workloadIdentity --resource-group $resourceGroup --query clientId -o tsv
    keyvaultName: # echo $kvName
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: ACRUSER
          objectType: secret
          objectVersion: ""
        - |
          objectName: ACRPASSWORD
          objectType: secret
          objectVersion: ""
    tenantId: # az account show --query tenantId -o tsv