version: 2.1
jobs:
  build:
    docker:
      - image: quay.io/buildah/stable
    resource_class: azuretour/aksrunner
    steps:
      - checkout
      - run:
          name: sanity-test
          command: |
            buildah version
      - run:
          name: Building-a-container
          command: |
            buildah bud --security-opt apparmor=unconfined -f ./Dockerfile -t circleci-runner-test:v1.0.0
workflows:
  build-workflow:
    jobs:
      - build